# Generated by Django 4.1.1 on 2022-09-30 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_start', models.CharField(choices=[('A', 'Mushroom Stew'), ('B', 'Fried Quail'), ('C', 'Garden Bits'), ('D', "Chef's Choice")], default='A', max_length=1)),
                ('meal_mid', models.CharField(choices=[('A', 'Bison Steak w/ SOTD'), ('B', 'Bison Roast w/ Potatoes'), ('C', 'Beet Salad w/ Goat Cheese')], default='A', max_length=1)),
                ('meal_end', models.CharField(choices=[('A', 'Mint Cake'), ('B', 'Butter Cookies')], default='A', max_length=1)),
                ('patron', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.patron')),
            ],
        ),
    ]
