# Generated by Django 4.1.1 on 2022-09-30 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_mealset'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mealset',
            old_name='meal_end',
            new_name='mealend',
        ),
        migrations.RenameField(
            model_name='mealset',
            old_name='meal_mid',
            new_name='mealmid',
        ),
        migrations.RenameField(
            model_name='mealset',
            old_name='meal_start',
            new_name='mealstart',
        ),
    ]
