# Generated by Django 4.1.1 on 2022-09-30 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='patron',
            name='services',
            field=models.ManyToManyField(to='main_app.service'),
        ),
    ]
